### ISSUE TITLE
Obtaining subscription key

### ISSUE THREAD

**Issue by Wisdom0063** [Chizzoz/mtn-momo-developer-basics#12]
How do I obtain the subscription key?
I use either of the primary key and secondary key and it didn't work

**Comment by Chizzoz** [comment]
Hi @wisdom0063 did you follow the guide in Readme file? Subscription keys, a primary and secondary one are generated for you when you subscribe to a product on Products page. You are able to view all your subscriptions on your user profile by clicking your name in top right corner. Hope that helps.
