### ISSUE TITLE
Add description of token request authorization headers to README.md

### ISSUE THREAD

**Issue by wilfredmulenga** [Chizzoz/mtn-momo-developer-basics#5]
the documentation on the token request, https://sandbox.momodeveloper.mtn.com/collection/token/ , does not specify how the authorization headers should be formatted. Adding wrongly formatted headers just returns a 500 timeout. We can specify that in the README.md for future reference. 

I can get this issue if that okay

**Comment by Chizzoz** [comment]
Yeah! I noticed that too, I have seen a lot of developers struggling with this in the *Support* section of the MoMo Developers Portal.

You're more than welcome, please take it up and edit README.md accordingly. Maybe step 4 can be Token generation and then step 5. Automation. Was thinking of adding those token generation steps but got a little tied up.

**Comment by wilfredmulenga** [comment]
I have made a PR #6 with the update

**Comment by Chizzoz** [comment]
Committed 🙌 
I noticed in the image you attached, Basic is followed by a full colon (:), like so, **Basic: xxx**, did your request work with the full colon? I usually just use **Basic space followed by B64 key**. Kindly confirm.

**Comment by WillzMu** [comment]
thanks for merging in it. I think I left out the colon when taking the screenshot. Should be there in the image now. thanks. This issue can be closed

**Comment by wilfredmulenga** [comment]
sorry about that. it doesnt work with the colon after basic. I have made PR #7 with the correct image

**Comment by Chizzoz** [comment]
Thanks! Committed the update.

**Comment by wilfredmulenga** [comment]
thanks. closing this issue

**Comment by Chizzoz** [comment]
Awesomeness! Are you able to create a branch where you can share code for your interaction with the API? JavaScript, Firebase or something?
